### ISSUE TITLE
Possible to see who you have invited (To bets and lobbies)

### ISSUE THREAD

**Issue by mgsdk** [THKIHA/PRJ4-webServer#49]

**Comment by niklasmmsoerensen** [comment]
Har tilføjet en table, der viser hvem der er inviteret i en lobby, når man ser på en lobby. 
![image](https://cloud.githubusercontent.com/assets/17593066/25554819/95f7a42c-2cd7-11e7-9478-75892db3eb3e.png)

Jeg ved ikke om vi skal have mere end det.
