### ISSUE TITLE
No text formatting on invite to lobby validation messages

### ISSUE THREAD

**Issue by niklasmmsoerensen** [THKIHA/PRJ4-webServer#55]
Fik sat nogle validation messages op, men kan ikke få teksten pæn, ligesom på andre sider. 

![image](https://cloud.githubusercontent.com/assets/17593066/25554722/e375dd7a-2cd4-11e7-82c3-48ac1b9c7e3b.png)

**Comment by mgsdk** [comment]
Fixed, removed h2 tag and inserted div tag instead with the required class.
