### ISSUE TITLE
Join bet link active even when joined

### ISSUE THREAD

**Issue by mgsdk** [THKIHA/PRJ4-webServer#56]

**Comment by niklasmmsoerensen** [comment]
Kan ikke umiddelbart løse det...
Hvis jeg forstår det korrekt er det igen lazy-loading der gør, at jeg ikke kan tilgå participants i et bet og dermed ikke tjekke, om brugeren er medlem af de bets. 
Jeg ved ikke om man bør smide info om dem i viewmodel eller få lavet noget eager loading igen.

**Comment by mgsdk** [comment]
Det letteste fra view siden er nok eager loading af hele skidtet

**Comment by niklasmmsoerensen** [comment]
Assigner lige @Traberg til at lave eager loading af lobbies. Så ordner jeg resten bagefter.
