### ISSUE TITLE
Join X-glyphicon kan muligvis ligne en knap, der sletter væddemålet.

### ISSUE THREAD

**Issue by niklasmmsoerensen** [THKIHA/PRJ4-webServer#71]
Jeg fik en kommentar fra en udefrakommende, at han i første omgang troede det var en knap, der slettede væddemålet. Vi kan lige overveje om det skal ændres. 
![image](https://cloud.githubusercontent.com/assets/17593066/25611811/b9d84128-2f28-11e7-96dd-b3dbaca4a49f.png)

**Comment by mgsdk** [comment]
Hvad med et minus i stedet for?
